### ISSUE TITLE
bot with login?

### ISSUE THREAD

**Issue by ghost** [VasenevEA/telegrambot#1]
hello @VasenevEA epic bot was wondering do you have any bot example where user says `/login <username> <password>` and `/register <username> <email> <password>` and will create user account?

I have this idea where I want users to register to my bot and there can store `ips` for game called `hackers` and once they login they can output `ip` by `/ip username`

If you do not have such example may ask you to help you with mine?

**Comment by VasenevEA** [comment]
Yes. I can do that. 
I will create new repo.
"HackerBot".

**Comment by ghost** [comment]
perfect, would you like me to create the repro?

**Comment by VasenevEA** [comment]
Yes

**Comment by ghost** [comment]
Will do

**Comment by VasenevEA** [comment]
OK
I will make fork

**Comment by ghost** [comment]
Invite sent

**Comment by ghost** [comment]
@VasenevEA Hows everything going what are using as auth Microsoft.Identy?
